### ISSUE TITLE
Status Check Feature Suggestion

### ISSUE THREAD

**Issue by eth-nn** [PhyXTGears-programming/timeclock#1]
Displaying who is currently signed in on the GUI

Could be static or scrolling or dynamic where it is static untill no more names can fit legibly so then it scrolls.

**Comment by NotQuiteApex** [comment]
If you meant the person's name of who is currently signing in or out, then this could be added. If not, I don't see a point to showing all the names of those signed in.

**Comment by rsammelson** [comment]
I agree with @notQuiteApex64 that there is no need for a list of people who are signed in.

In the future we could make it so you can dial the Raspberry Pi connected to to the phone system and it would have the ability to read off the people present in a specific sub-team (e.g. programming or mechanical).

**Comment by eth-nn** [comment]
Initially I thought of it as a way to generally and easily check if someone in the shop has signed in yet.

I guess another way to implement this without using a display is to have a command like
 `!check <username>` which then prints the status. Like
`<Persons Full Name> has been clocked <in/out> since <timestamp from file>`
Where the username can either be the persons full name or login but the printout is always their name.

**Comment by rsammelson** [comment]
@notQuiteApex64 Is this feature working yet?

**Comment by NotQuiteApex** [comment]
GUI displays status with a single letter, may expand on it later however.
