### ISSUE TITLE
Clearing Screen

### ISSUE THREAD

**Issue by eth-nn** [PhyXTGears-programming/timeclock#4]
I might do it myself, but want to put it out there.

It might be better to clear the screen fully by setting this up

```
import os

def cls()
    os.system("CLS")
```

And calling cls rather than printing a bunch of lines. 
This means better data security and experience since some people have gotten confused when the cursor accidentally moves above the input line.

**Comment by NotQuiteApex** [comment]
So long as it works for both IDLE and any operating system's terminal or command line, then it's good.

Side note, once everything is implemented properly (it won't look pretty), I'll be working on a GUI with tkinter to use rather than the terminal.
