### ISSUE TITLE
Autoclockout issue

### ISSUE THREAD

**Issue by PhyXTGears-1720** [PhyXTGears-programming/timeclock#5]
Autoclockout anytime just after 12:00 instead of just right at 12:00

**Comment by NotQuiteApex** [comment]
could i ask why this would be necessary? i dont see the point of making any sort of delay since it works fine as is.

**Comment by rsammelson** [comment]
@notQuiteApex64 Is this fixed?

**Comment by rsammelson** [comment]
@notQuiteApex64 This is fixed if you are auto-signed-out at 12:00, but that is changed to a regular sign out if you sign out before 5.

**Comment by NotQuiteApex** [comment]
that is correct, and the autosign out is kept simply for record. the current time calculator simply ignores autoclockouts.
