### ISSUE TITLE
Spreadsheet generator of names and total time

### ISSUE THREAD

**Issue by NotQuiteApex** [PhyXTGears-programming/timeclock#8]
if jobs are implemented, then have it be sorted by jobs. otherwise alphabetically.

**Comment by rsammelson** [comment]
@notQuiteApex64 I am writing a Python program to analyze hours. That will be located in a different repository. This is not relevant here.

**Comment by NotQuiteApex** [comment]
it would be more appropriate in the same repository so as to be used by the program to generate a spreadsheet every so often.

**Comment by rsammelson** [comment]
@notQuiteApex64 I think it would be best to have it as a separate repository, at most we can have the other repository be a dependency of this one. I think the best setup would be to have the other repository be an optional add on that is installed separately. Also, do you really want the 50+ commits necessary to do analysis on the hours to crowd this repository?
I started another repository here: [PhyXTGears-Programming/timeclock-hours](https://github.com/PhyXTGears-programming/timeclock-hours.)
